// PB DevKit CLI — Integration Tests
//
// Tests the CLI command routing and logic via pb_devkit_cli::execute_command().
// Uses pb_devkit_core::pbl_writer to create test PBL files on the fly.

use pb_devkit_cli::execute_command;
use pb_devkit_core::pbl_writer::{PblWriter, PblEncoding};
use std::io::Write;
use std::path::PathBuf;
use std::fs;

// ── Helpers ────────────────────────────────────────────────────────────

/// Create a temporary directory that is cleaned up on Drop.
struct TempDir {
    path: PathBuf,
}

impl TempDir {
    fn new(prefix: &str) -> Self {
        let dir = std::env::temp_dir().join(format!("pbdevkit_test_{}", prefix));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("Failed to create temp dir");
        TempDir { path: dir }
    }

    fn join(&self, name: &str) -> PathBuf {
        self.path.join(name)
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

/// Create a minimal test PBL file with one source entry.
fn create_test_pbl(dir: &TempDir, name: &str) -> PathBuf {
    let pbl_path = dir.join(name);
    let mut writer = PblWriter::new(12, PblEncoding::Ansi);
    // obj_type: 6 = USEROBJECT; name must include extension (.sru)
    writer.add_entry("u_test_object.sru", 6, "// Test source\n// Generated by integration test".as_bytes().to_vec(), None);
    let bytes = writer.to_bytes().expect("PblWriter::to_bytes failed");
    let mut file = fs::File::create(&pbl_path).expect("Failed to create PBL file");
    file.write_all(&bytes).expect("Failed to write PBL bytes");
    pbl_path
}

/// Create a test PBL with multiple entries.
fn create_multi_pbl(dir: &TempDir, name: &str) -> PathBuf {
    let pbl_path = dir.join(name);
    let mut writer = PblWriter::new(12, PblEncoding::Ansi);
    // obj_type: 2=WINDOW(.srw), 1=DATAWINDOW(.srd), 4=FUNCTION(.srf)
    writer.add_entry("w_main.srw", 2, "// Main window".as_bytes().to_vec(), None);
    writer.add_entry("dw_customer.srd", 1, "// Customer grid".as_bytes().to_vec(), None);
    writer.add_entry("f_calc.srf", 4, "// Calculation function".as_bytes().to_vec(), None);
    let bytes = writer.to_bytes().expect("PblWriter::to_bytes failed");
    let mut file = fs::File::create(&pbl_path).expect("Failed to create PBL file");
    file.write_all(&bytes).expect("Failed to write PBL bytes");
    pbl_path
}

// ── Help / Usage tests ─────────────────────────────────────────────────

#[test]
fn help_output_has_all_expected_sections() {
    let output = execute_command("help", &[]).expect("help should succeed");
    assert!(output.contains("PB DevKit CLI"), "brand");
    assert!(output.contains("Usage:"), "usage section");
    assert!(output.contains("Commands:"), "commands section");
    assert!(output.contains("Examples:"), "examples section");
    assert!(output.contains("parse"), "parse command");
    assert!(output.contains("migrate"), "migrate command");
    assert!(output.contains("build"), "build command");
    assert!(output.contains("interactive"), "interactive mode");
}

// ── Unknown command test ───────────────────────────────────────────────

#[test]
fn unknown_command_returns_meaningful_error() {
    let err = execute_command("foobar", &[]).unwrap_err();
    assert!(err.contains("Unknown command"), "error should mention unknown");
    assert!(err.contains("foobar"), "error should echo the bad command");
}

// ── Doctor test (no file needed) ────────────────────────────────────────

#[test]
fn doctor_produces_some_output() {
    let result = execute_command("doctor", &[]);
    // Doctor may succeed or fail depending on environment; either is a valid route
    match result {
        Ok(output) => assert!(!output.is_empty(), "doctor output should not be empty"),
        Err(_) => { /* environment-dependent failure is OK */ }
    }
}

// ── PBL parse / info / list tests ──────────────────────────────────────

#[test]
fn parse_valid_pbl_succeeds() {
    let dir = TempDir::new("parse");
    let pbl = create_test_pbl(&dir, "test.pbl");

    let result = execute_command("parse", &[pbl.to_string_lossy().to_string()]);
    assert!(result.is_ok(), "Parsing valid PBL should succeed: {:?}", result.err());
    let output = result.unwrap();
    assert!(!output.is_empty(), "Parse output should not be empty");
}

#[test]
fn parse_nonexistent_pbl_fails() {
    let result = execute_command("parse", &["/nonexistent/nope.pbl".to_string()]);
    assert!(result.is_err(), "Parsing nonexistent file should fail");
}

#[test]
fn info_command_returns_pbl_metadata() {
    let dir = TempDir::new("info");
    let pbl = create_test_pbl(&dir, "test.pbl");

    let result = execute_command("info", &[pbl.to_string_lossy().to_string()]);
    assert!(result.is_ok(), "Info should succeed: {:?}", result.err());
    let output = result.unwrap();
    assert!(!output.is_empty(), "Info output should not be empty");
}

#[test]
fn list_command_shows_entries() {
    let dir = TempDir::new("list");
    let pbl = create_multi_pbl(&dir, "multi.pbl");

    let result = execute_command("list", &[pbl.to_string_lossy().to_string()]);
    assert!(result.is_ok(), "List should succeed: {:?}", result.err());
    let output = result.unwrap();
    // PBL entries include extensions: w_main.srw, dw_customer.srd, f_calc.srf
    assert!(output.contains("w_main"), "should contain window entry");
    assert!(output.contains("dw_customer"), "should contain DW entry");
    assert!(output.contains("f_calc"), "should contain function entry");
}

#[test]
fn pbl_alias_works_for_parse() {
    let dir = TempDir::new("pbl_alias");
    let pbl = create_test_pbl(&dir, "test.pbl");

    let result = execute_command("pbl", &[pbl.to_string_lossy().to_string()]);
    assert!(result.is_ok(), "pbl alias should work: {:?}", result.err());
}

#[test]
fn export_command_outputs_source() {
    let dir = TempDir::new("export");
    let pbl = create_test_pbl(&dir, "test.pbl");

    // Entry name must include extension: u_test_object.sru
    let result = execute_command("export", &[
        pbl.to_string_lossy().to_string(),
        "u_test_object.sru".to_string(),
    ]);
    assert!(result.is_ok(), "Export should succeed: {:?}", result.err());
    let output = result.unwrap();
    assert!(output.contains("// Test source"), "should contain source text");
}

#[test]
fn export_nonexistent_entry_fails() {
    let dir = TempDir::new("export_bad");
    let pbl = create_test_pbl(&dir, "test.pbl");

    let result = execute_command("export", &[
        pbl.to_string_lossy().to_string(),
        "nonexistent_entry.sru".to_string(),
    ]);
    assert!(result.is_err(), "Exporting nonexistent entry should fail");
}

// ── PE file-type test ──────────────────────────────────────────────────

#[test]
fn file_type_returns_something() {
    // Use a known existing file (Cargo.toml) — should detect as "Unknown" or similar
    let cargo_toml = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml");
    let result = execute_command("file-type", &[cargo_toml.to_string_lossy().to_string()]);
    // file-type may succeed or fail; we just verify it routes correctly
    match result {
        Ok(output) => assert!(!output.is_empty()),
        Err(e) => assert!(!e.contains("Unknown command"), "should not be unknown command"),
    }
}

// ── Project detect test ────────────────────────────────────────────────

#[test]
fn project_detect_on_nonexistent_path() {
    let result = execute_command("project", &["/nonexistent/path".to_string()]);
    match result {
        Ok(_) => { /* OK */ }
        Err(e) => {
            // Must not be "Unknown command" — must be a domain error
            assert!(!e.contains("Unknown command"),
                "project should route: got '{}'", e);
        }
    }
}

#[test]
fn detect_alias_works() {
    let result = execute_command("detect", &["/nonexistent/path".to_string()]);
    match result {
        Ok(_) => {}
        Err(e) => assert!(!e.contains("Unknown command"), "detect alias should route"),
    }
}

// ── Search test ────────────────────────────────────────────────────────

#[test]
fn search_on_nonexistent_path() {
    let result = execute_command("search", &["/nonexistent".to_string(), "hello".to_string()]);
    match result {
        Ok(_) => {}
        Err(e) => assert!(!e.contains("Unknown command"), "search should route"),
    }
}

#[test]
fn search_regex_routes_correctly() {
    let result = execute_command("search-regex", &["/nonexistent".to_string(), r"\d+".to_string()]);
    match result {
        Ok(_) => {}
        Err(e) => assert!(!e.contains("Unknown command"), "search-regex should route"),
    }
}

// ── Pack to PBL test ───────────────────────────────────────────────────

#[test]
fn pack_to_pbl_routes_correctly() {
    let dir = TempDir::new("pack");
    let src_dir = dir.join("sources");
    fs::create_dir_all(&src_dir).unwrap();
    let out_pbl = dir.join("output.pbl");

    let result = execute_command("pack-to-pbl", &[
        src_dir.to_string_lossy().to_string(),
        out_pbl.to_string_lossy().to_string(),
    ]);
    match result {
        Ok(output) => {
            assert!(!output.is_empty());
            // output PBL may or may not exist depending on whether sources were found
        }
        Err(e) => {
            // May fail if no source files; but must route correctly
            assert!(!e.contains("Unknown command"));
        }
    }
}

// ── All command coverage test ──────────────────────────────────────────

#[test]
fn all_30_commands_are_routable() {
    let all_cmds: Vec<(&str, Vec<String>)> = vec![
        ("parse", vec!["/none".to_string()]),
        ("info", vec!["/none".to_string()]),
        ("list", vec!["/none".to_string()]),
        ("export", vec!["/none".to_string(), "obj".to_string()]),
        ("export-pbl", vec!["/none".to_string(), "/out".to_string()]),
        ("file-type", vec!["/none".to_string()]),
        ("analyze-pe", vec!["/none".to_string()]),
        ("extract-pbd", vec!["/none".to_string(), "/out".to_string()]),
        ("project", vec!["/none".to_string()]),
        ("find-pbl", vec!["/none".to_string()]),
        ("scan-export", vec!["/none".to_string(), "/out".to_string()]),
        ("pack-to-pbl", vec!["/none".to_string(), "/out".to_string()]),
        ("doctor", vec![]),
        ("search", vec!["/none".to_string(), "q".to_string()]),
        ("search-type", vec!["/none".to_string(), "Window".to_string()]),
        ("search-regex", vec!["/none".to_string(), ".*".to_string()]),
        ("analyze-dw", vec!["/none".to_string()]),
        ("dw-sql", vec!["/none".to_string()]),
        ("list-decompile", vec!["/none".to_string()]),
        ("decompile", vec!["/none".to_string(), "obj".to_string()]),
        ("decompile-all", vec!["/none".to_string(), "/out".to_string()]),
        ("report", vec!["/none".to_string()]),
        ("export-report", vec!["/none".to_string(), "/out".to_string()]),
        ("diff", vec!["/a".to_string(), "/b".to_string()]),
        ("workflow", vec!["/none".to_string()]),
        ("refactor", vec!["/none".to_string()]),
        ("snapshot", vec!["/none".to_string()]),
        ("review", vec!["/none".to_string()]),
        ("autoexport", vec!["/none".to_string()]),
        ("migrate", vec!["/none".to_string()]),
        ("build", vec!["/none".to_string(), "app".to_string()]),
    ];

    let routed = all_cmds.iter().filter(|(cmd, args)| {
        match execute_command(cmd, args) {
            Ok(_) => true,
            Err(e) => !e.contains("Unknown command"),
        }
    }).count();

    assert_eq!(routed, all_cmds.len(),
        "All {} commands must be routable, only {} routed",
        all_cmds.len(), routed);
}
